# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell"
ZSH_THEME="risto"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(ant autojump brew cap gem gitfast git-flow github history-substring-search mvn osx rails3 rake ruby rvm svn bundler)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

export JAVA_HOME=/opt/jdk7
export M2_HOME=/opt/maven
export JAVA_OPTS="-XX:MaxPermSize=128m -XX:PermSize=128m"
export MAVEN_OPTS="-Dmaven.artifact.threads=3 -Xmx768m"
export PATH=/opt/play-1.2.4:$JAVA_HOME/bin:$PATH:$M2_HOME/bin

export BUILD_ENV_CODE=linuxdev


